#!/bin/bash
#
# Start Cobalt Strike Aggressor Script
#

java -XX:ParallelGCThreads=4 -XX:+AggressiveHeap -XX:+UseParallelGC -classpath ./cobaltstrike.jar -javaagent:CSAgent.jar=f38eb3d1a335b252b58bc2acde81b542 -Duser.language=en aggressor.headless.Start $*
